// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfenpnjoedtfbtnoerda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmZW5wbmpvZWR0ZmJ0bm9lcmRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMTkwMDEsImV4cCI6MjA1OTU5NTAwMX0.boKutLwq1pIJfPD38UCY8MYkMkEtp8T6-egOxGsrAdo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});